### ISSUE TITLE
cannot load such file -- active_support/core_ext (LoadError)

### ISSUE THREAD

**Issue by matecode** [csbhalerao/swag_gen_factory#1]
Hi. I wanted to try you script (Mac Big Sur, ruby 3.0 installed threw homebrew) but i get the following error:

```
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- active_support/core_ext (LoadError)
	from <internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from swag_gen_factory/gen_network_code.rb:2:in `<main>'
```

Google did not help me, maybe you can. Thx

**Comment by dev4y0u** [comment]
Change first lines in the script to 
require 'json'
**require 'active_support'**
require 'active_support/core_ext'

You have to load 'active_support' before you can use require 'active_support/core_ext'

Further I noticed that you should generate the swagger file from the "swagger code gen". I used NSwag first and got an error: "gen_network_code.rb:337:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)" which was raised by an "invalid" generated json file.

**Comment by albertocavalcante** [comment]
@dev4y0u thanks! Could you share a sample Swagger which is working for you? I'm stuck with the nil error :/
